.Dd 2012-Aug-13               \" DATE
.Dt real-git-rcmp 1      \" Program name and manual section number 
.Os Unix
.Sh NAME                 \" Section Header - required - don't modify 
.Nm real-git-rcmp
.\" The following lines are read in generating the apropos(man -k) database. Use only key
.\" words here as the database is built based on the words here and in the .ND line. 
.\" .Nm RCMP for Real Git
.\" Use .Nm macro to designate other names for the documented program.
.Nd Allows "real git" repos to use RCMP Web service hooks.
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Ar api_endpoint
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Nm
allows one to use the RCMP Web service hook from repos not hosted on GitHub.
See
.Ar https://github.com/programble/rcmp
for more information about RCMP.
.Nm
uses libgit2 to retrieve information about the git repository, libjson to
format the JSON data, and libAmy to send the data to the URL specified by
.Ar api_endpoint .
.Pp                      \" Inserts a space
.Bl -tag -width -indent  \" Differs from above in tag removed 
.It api_endpoint
The URL of the API.
.El                      \" Ends the list
.Pp
.Sh ENVIRONMENT
.Bl -tag -width "GIT_DIR" -indent
.It Ev GIT_DIR
If set, use
.Ar GIT_DIR
for the path to the git repository.  If not set, 
.Nm
will try to use current directory.  This is set automatically by git while
running hooks.
.Sh SEE ALSO
.\" List links in ascending order by section, alphabetically within a section.
.\" Please do not reference files that do not exist without filing a bug report
.Xr git 1 ,
.Xr githooks 5 .
.\" .Sh BUGS              \" Document known, unremedied bugs
.\" .Sh HISTORY           \" Document history if command behaves in a unique manner